### ISSUE TITLE
weird extra </a>

### ISSUE THREAD

**Issue by amyxzhang** [haystack/eyebrowse-chrome-ext#17] opened 2015-03-22 23:30 UTC
![untitled](https://cloud.githubusercontent.com/assets/1301962/6772088/e31c7640-d0c9-11e4-958f-59953f582fba.png)

**Comment by amyxzhang** [comment] 2015-03-22 23:37
@joshblum just wondering have you been updating the chrome ext in the store?

**Comment by joshblum** [comment] 2015-03-22 23:59
Hmm no I've only been pushing to the repository. I'm not sure if I even have access

**Comment by joshblum** [comment] 2015-03-23 23:31
any steps to reproduce? I haven't noticed this ( i also havn't seen people popping up recently maybe since i'm pointing to dev server?)

**Comment by amyxzhang** [comment] 2015-03-24 01:03
I'll keep an eye out. i went back to that page and now there's no popup at all weirdly. although I did see it on another occasion but now I've forgotten where.

**Comment by joshblum** [comment] 2015-03-27 17:05
should be closed by #13

**Closed** 2015-03-27 17:51 UTC
